[target.thumbv7m-none-eabi]
runner = "sudo qemu-system-arm -serial pty -cpu cortex-m3 -machine netduino2 -semihosting-config enable=on,target=native -kernel"
# runner = "sudo qemu_stm32/arm-softmmu/qemu-system-arm -cpu cortex-m3 -serial stdio -machine stm32-f103c8 -kernel"

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x"
]

[build]
target = "thumbv7m-none-eabi"
